name: rusty_chacha
description: >
  A Flutter library for fast ChaCha20-Poly1305 encryption, powered by Rust 
version: 0.0.5
homepage: https://github.com/brookman/rusty_chacha
repository: https://github.com/brookman/rusty_chacha
issue_tracker: https://github.com/brookman/rusty_chacha/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.0.15
  collection: ^1.18.0
  ffi: ^2.0.1
  flutter_rust_bridge: 2.0.0-dev.31
  freezed_annotation: ^2.2.0
  uuid: ^4.1.0  # TODO https://github.com/fzyzcjy/flutter_rust_bridge/issues/1147

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  ffigen: ^11.0.0
  freezed: ^2.2.1
  test: ^1.22.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
