name: rusty_chacha
description: >
  A Flutter library for fast ChaCha20-Poly1305 encryption, powered by Rust 
version: 0.7.3
homepage: https://github.com/brookman/rusty_chacha
repository: https://github.com/brookman/rusty_chacha
issue_tracker: https://github.com/brookman/rusty_chacha/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rusty_chacha_dart: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
