[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# [target.aarch64-linux-android]
# rustflags = ["-C", "target-feature=+neon", "--cfg", "chacha20_force_neon"]

[target.aarch64-apple-ios]
rustflags = ["-C", "target-feature=+neon", "--cfg", "chacha20_force_neon"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+neon", "--cfg", "chacha20_force_neon"]
