[package]
name = "embedded_rusty_chacha"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
flutter_rust_bridge_codegen = "2.4.0"
anyhow = "1.0.89"
cbindgen = "0.27.0"

[dev-dependencies]
divan = "0.1.14"
sysinfo = "0.31.4"
rand = "0.8.5"

[[bench]]
name = "example"
harness = false

[dependencies]
anyhow = "1.0.89"
flutter_rust_bridge = "=2.4.0"
chacha20poly1305 = "0.10.1"
zstd = "0.13.2"
