name: rusty_chacha_dart
description: >
  A Flutter library for fast ChaCha20-Poly1305 encryption, powered by Rust 
version: 0.7.0
homepage: https://github.com/brookman/rusty_chacha
repository: https://github.com/brookman/rusty_chacha
issue_tracker: https://github.com/brookman/rusty_chacha/issues

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: ^2.4.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.13
  ffigen: ^14.0.1
  freezed: ^2.5.7
  test: ^1.25.7
