name: Create Release(s)

on:
  workflow_dispatch:
    inputs:
      version_parameters:
        description: 'Parameters to pass to "melos version"'
        required: true
        default: ' '
        type: choice
        options:
          - '--'
          - '--prerelease'
          - '--graduate'
      manual_version:
        description: 'Manual version'
        required: false
        default: ''
        type: string

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Setup git
        run: |
          git config user.name "RustyChahaActionsBot"
          git config user.email "rc-p90@bluemail.ch"
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v2

      - name: Create the new version(s)
        #run: melos version --yes ${{ inputs.version_parameters }}
        run: melos version --yes -V rusty_chacha:${{ inputs.manual_version }} -V rusty_chacha_dart:${{ inputs.manual_version }}

      - name: Push created version commit
        run: git push
      - name: Push modified tags
        run: git push --tags
